services:
  app:
    image: rental-server:latest
    ports:
      - "8080:8080"
    dns:
      - 8.8.8.8
    depends_on:
      - mariadb
    environment:
      PROD_MARIADB_DATASOURCE_USERNAME: ${PROD_MARIADB_DS_USERNAME}
      PROD_MARIADB_DATASOURCE_PASSWORD: ${PROD_MARIADB_DS_PASSWORD}
      PROD_MARIADB_DATASOURCE_URL: jdbc:mariadb://${PROD_MARIADB_DS_HOST}:${PROD_MARIADB_DS_PORT}/rental-db
      PROD_MARIADB_DATASOURCE_DRIVER_CLASS_NAME: ${PROD_MARIADB_DS_DRIVER_CLASS_NAME}

      TEST_DATASOURCE_USERNAME: ${TEST_DS_USERNAME}
      TEST_DATASOURCE_PASSWORD: ${TEST_DS_PASSWORD}
      TEST_DATASOURCE_URL: "jdbc:h2:mem:testdb"
      TEST_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"

      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_PORT: ${MAIL_PORT}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      ADMIN_MAIL_ADDRESS: ${ADMIN_MAIL}
      RENTALGADGET_IMAGES_PATH: ${RENTALGADGET_IMAGES_PATH}
      RENTALGADGET_EXCELS_PATH: ${RENTALGADGET_EXCELS_PATH}
      RENTALGADGET_STAGING_PATH: ${RENTALGADGET_STAGING_PATH}
      MAYA_CHECKOUT_SANDBOX_URL: ${MAYA_CHECKOUT_SANDBOX_URL}
      MAYA_PUBLIC_KEY_SANDBOX: ${MAYA_PUBLIC_KEY_SANDBOX}
      MAYA_SECRET_KEY_SANDBOX: ${MAYA_SECRET_KEY_SANDBOX}


    volumes:
      - ./gadget-assets:/server/gadget-assets
            
  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yaml"
    volumes:
      - ./ngrok.yaml:/etc/ngrok.yaml
    ports:
      - "4040:4040"
    depends_on:
      - app

volumes:
  mariadb_data:
