/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowToRentRouteImport } from './routes/how-to-rent'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as RegisterCreateRouteImport } from './routes/register/create'
import { Route as RegisterConfirmRouteImport } from './routes/register/confirm'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToRentRoute = HowToRentRouteImport.update({
  id: '/how-to-rent',
  path: '/how-to-rent',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCreateRoute = RegisterCreateRouteImport.update({
  id: '/register/create',
  path: '/register/create',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterConfirmRoute = RegisterConfirmRouteImport.update({
  id: '/register/confirm',
  path: '/register/confirm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/home': typeof HomeRoute
  '/how-to-rent': typeof HowToRentRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/register/confirm': typeof RegisterConfirmRoute
  '/register/create': typeof RegisterCreateRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/home': typeof HomeRoute
  '/how-to-rent': typeof HowToRentRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/register/confirm': typeof RegisterConfirmRoute
  '/register/create': typeof RegisterCreateRoute
  '/register': typeof RegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/home': typeof HomeRoute
  '/how-to-rent': typeof HowToRentRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/register/confirm': typeof RegisterConfirmRoute
  '/register/create': typeof RegisterCreateRoute
  '/register/': typeof RegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/home'
    | '/how-to-rent'
    | '/login'
    | '/shop'
    | '/register/confirm'
    | '/register/create'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/home'
    | '/how-to-rent'
    | '/login'
    | '/shop'
    | '/register/confirm'
    | '/register/create'
    | '/register'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/home'
    | '/how-to-rent'
    | '/login'
    | '/shop'
    | '/register/confirm'
    | '/register/create'
    | '/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  HomeRoute: typeof HomeRoute
  HowToRentRoute: typeof HowToRentRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  RegisterConfirmRoute: typeof RegisterConfirmRoute
  RegisterCreateRoute: typeof RegisterCreateRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-rent': {
      id: '/how-to-rent'
      path: '/how-to-rent'
      fullPath: '/how-to-rent'
      preLoaderRoute: typeof HowToRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/create': {
      id: '/register/create'
      path: '/register/create'
      fullPath: '/register/create'
      preLoaderRoute: typeof RegisterCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/confirm': {
      id: '/register/confirm'
      path: '/register/confirm'
      fullPath: '/register/confirm'
      preLoaderRoute: typeof RegisterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  HomeRoute: HomeRoute,
  HowToRentRoute: HowToRentRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  RegisterConfirmRoute: RegisterConfirmRoute,
  RegisterCreateRoute: RegisterCreateRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
