package com.gadget.rental.shared;

import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.ZonedDateTime;

import jakarta.mail.BodyPart;
import jakarta.mail.Message.RecipientType;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeBodyPart;
import jakarta.mail.internet.MimeMessage;
import jakarta.mail.internet.MimeMultipart;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

@Service
public class EmailSenderService {

    private JavaMailSender emailSender;
    private final String name = "Mr. Ivan Velasco";
    private final String position = "Supervisor";
    private final String email = "book@vantripperstravelandtour.com";

    @Value("${admin.mail.address}")
    private String adminGmail;

    @Autowired
    public EmailSenderService(JavaMailSender emailSender) {
        this.emailSender = emailSender;
    }

    @Async
    public void sendClientVerificationCode(String receiverAddress, String code) throws MessagingException {
        MimeMessage mimeMessage = emailSender.createMimeMessage();
        mimeMessage.setFrom(adminGmail);
        mimeMessage.setRecipient(RecipientType.TO, new InternetAddress(receiverAddress));
        mimeMessage.setSubject("Verification Code");
        String content = String.format("<!doctype html>\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                + "  <head>\n"
                + "    <title></title>\n"
                + "    <!--[if !mso]><!-->\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <!--<![endif]-->\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "    <style type=\"text/css\">\n"
                + "      #outlook a { padding:0; }\n"
                + "      body { margin:0;padding:0;-webkit-text-size-adjust:100%%;-ms-text-size-adjust:100%%; }\n"
                + "      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }\n"
                + "      img { border:0;height:auto;line-height:100%%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }\n"
                + "      p { display:block;margin:13px 0; }\n"
                + "    </style>\n"
                + "    <!--[if mso]>\n"
                + "    <noscript>\n"
                + "    <xml>\n"
                + "    <o:OfficeDocumentSettings>\n"
                + "      <o:AllowPNG/>\n"
                + "      <o:PixelsPerInch>96</o:PixelsPerInch>\n"
                + "    </o:OfficeDocumentSettings>\n"
                + "    </xml>\n"
                + "    </noscript>\n"
                + "    <![endif]-->\n"
                + "    <!--[if lte mso 11]>\n"
                + "    <style type=\"text/css\">\n"
                + "      .mj-outlook-group-fix { width:100%% !important; }\n"
                + "    </style>\n"
                + "    <![endif]-->\n"
                + "    <!--[if !mso]><!-->\n"
                + "    <link href=\"https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700\" rel=\"stylesheet\" type=\"text/css\">\n"
                + "    <link href=\"https://fonts.googleapis.com/css?family=Cabin:400,700\" rel=\"stylesheet\" type=\"text/css\">\n"
                + "    <style type=\"text/css\">\n"
                + "      @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);\n"
                + "      @import url(https://fonts.googleapis.com/css?family=Cabin:400,700);\n"
                + "    </style>\n"
                + "    <!--<![endif]-->\n"
                + "    <style type=\"text/css\">\n"
                + "      @media only screen and (min-width:480px) {\n"
                + "        .mj-column-per-100 { width:100%% !important; max-width: 100%%; }\n"
                + "      }\n"
                + "    </style>\n"
                + "    <style media=\"screen and (min-width:480px)\">\n"
                + "      .moz-text-html .mj-column-per-100 { width:100%% !important; max-width: 100%%; }\n"
                + "    </style>\n"
                + "    <style type=\"text/css\"></style>\n"
                + "    <style type=\"text/css\">\n"
                + "    .hide_on_mobile { display: none !important;} \n"
                + "    @media only screen and (min-width: 480px) { .hide_on_mobile { display: block !important;} }\n"
                + "    .hide_section_on_mobile { display: none !important;} \n"
                + "    @media only screen and (min-width: 480px) { \n"
                + "        .hide_section_on_mobile { \n"
                + "            display: table !important;\n"
                + "        } \n"
                + "        div.hide_section_on_mobile { \n"
                + "            display: block !important;\n"
                + "        }\n"
                + "    }\n"
                + "    .hide_on_desktop { display: block !important;} \n"
                + "    @media only screen and (min-width: 480px) { .hide_on_desktop { display: none !important;} }\n"
                + "    .hide_section_on_desktop { \n"
                + "        display: table !important;\n"
                + "        width: 100%%;\n"
                + "    } \n"
                + "    @media only screen and (min-width: 480px) { .hide_section_on_desktop { display: none !important;} }\n"
                + "    p, h1, h2, h3 {\n"
                + "        margin: 0px;\n"
                + "    }\n"
                + "    ul, li, ol {\n"
                + "      font-size: 11px;\n"
                + "      font-family: Ubuntu, Helvetica, Arial;\n"
                + "    }\n"
                + "    a {\n"
                + "        text-decoration: none;\n"
                + "        color: inherit;\n"
                + "    }\n"
                + "    @media only screen and (max-width:480px) {\n"
                + "        .mj-column-per-100 { width:100%%!important; max-width:100%%!important; }\n"
                + "        .mj-column-per-100 > .mj-column-per-100 { width:100%%!important; max-width:100%%!important; }\n"
                + "    }\n"
                + "    .mj-column-per-100 [class^=\"mj-column-per-\"] {\n"
                + "        line-height: normal;\n"
                + "    }\n"
                + "    .mj-button-full a {\n"
                + "        display: block !important;\n"
                + "    }\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body style=\"word-spacing:normal;background-color:#FFFFFF;\">\n"
                + "    <div style=\"background-color:#FFFFFF;\">\n"
                + "      <!--[if mso | IE]><table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" role=\"presentation\" style=\"width:600px;\" width=\"600\" ><tr><td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\"><![endif]-->\n"
                + "      <div style=\"margin:0px auto;max-width:600px;\">\n"
                + "        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%%;\">\n"
                + "          <tbody>\n"
                + "            <tr>\n"
                + "              <td style=\"direction:ltr;font-size:0px;padding:9px 0px 9px 0px;text-align:center;\">\n"
                + "                <!--[if mso | IE]><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td class=\"\" style=\"vertical-align:top;width:600px;\" ><![endif]-->\n"
                + "                <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%%;\">\n"
                + "                  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%%\">\n"
                + "                    <tbody>\n"
                + "                      <tr>\n"
                + "                        <td align=\"left\" style=\"font-size:0px;padding:15px 15px 15px 15px;word-break:break-word;\">\n"
                + "                          <div style=\"font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1.5;text-align:left;color:#000000;\">\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><strong><span style=\"font-size: 12px;\">Good day,&nbsp;</span></strong></p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Thank you for your request. To complete the verification process, please use the following code:</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Verification Code: %s<br>Enter this code on the verification page to confirm your identity.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Note:<br>This verification code is valid for the next 3 minutes. If you did not request this verification, please disregard this email.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><br>For security purposes, please do not share this code with anyone.<br>If you need further assistance, feel free to contact us.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Thank you for choosing Trippers' Gear Rental PH. We look forward to finalizing your rental agreement.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Best regards,<br>%s<br>%s<br>Trippers' Gear Rental PH<br>%s</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p></div>\n"
                + "                        </td>\n"
                + "                      </tr>\n"
                + "                    </tbody>\n"
                + "                  </table>\n"
                + "                </div>\n"
                + "              </td>\n"
                + "            </tr>\n"
                + "          </tbody>\n"
                + "        </table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </body>\n"
                + "</html>", code, name, position, email);
        mimeMessage.setContent(content, "text/html; charset=utf-8");
        emailSender.send(mimeMessage);
    }

    @Async
    public void sendAdminVerificationCode(String code) throws MessagingException {
        MimeMessage mimeMessage = emailSender.createMimeMessage();
        mimeMessage.setFrom(adminGmail);
        mimeMessage.setRecipient(RecipientType.TO, new InternetAddress(adminGmail));
        mimeMessage.setSubject("Verification Code");

        String content = String.format("<!doctype html>\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                + "  <head>\n"
                + "    <title></title>\n"
                + "    <!--[if !mso]><!-->\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <!--<![endif]-->\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "    <style type=\"text/css\">\n"
                + "      #outlook a { padding:0; }\n"
                + "      body { margin:0;padding:0;-webkit-text-size-adjust:100%%;-ms-text-size-adjust:100%%; }\n"
                + "      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }\n"
                + "      img { border:0;height:auto;line-height:100%%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }\n"
                + "      p { display:block;margin:13px 0; }\n"
                + "    </style>\n"
                + "    <!--[if mso]>\n"
                + "    <noscript>\n"
                + "    <xml>\n"
                + "    <o:OfficeDocumentSettings>\n"
                + "      <o:AllowPNG/>\n"
                + "      <o:PixelsPerInch>96</o:PixelsPerInch>\n"
                + "    </o:OfficeDocumentSettings>\n"
                + "    </xml>\n"
                + "    </noscript>\n"
                + "    <![endif]-->\n"
                + "    <!--[if lte mso 11]>\n"
                + "    <style type=\"text/css\">\n"
                + "      .mj-outlook-group-fix { width:100%% !important; }\n"
                + "    </style>\n"
                + "    <![endif]-->\n"
                + "    <!--[if !mso]><!-->\n"
                + "    <link href=\"https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700\" rel=\"stylesheet\" type=\"text/css\">\n"
                + "    <link href=\"https://fonts.googleapis.com/css?family=Cabin:400,700\" rel=\"stylesheet\" type=\"text/css\">\n"
                + "    <style type=\"text/css\">\n"
                + "      @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);\n"
                + "      @import url(https://fonts.googleapis.com/css?family=Cabin:400,700);\n"
                + "    </style>\n"
                + "    <!--<![endif]-->\n"
                + "    <style type=\"text/css\">\n"
                + "      @media only screen and (min-width:480px) {\n"
                + "        .mj-column-per-100 { width:100%% !important; max-width: 100%%; }\n"
                + "      }\n"
                + "    </style>\n"
                + "    <style media=\"screen and (min-width:480px)\">\n"
                + "      .moz-text-html .mj-column-per-100 { width:100%% !important; max-width: 100%%; }\n"
                + "    </style>\n"
                + "    <style type=\"text/css\"></style>\n"
                + "    <style type=\"text/css\">\n"
                + "    .hide_on_mobile { display: none !important;} \n"
                + "    @media only screen and (min-width: 480px) { .hide_on_mobile { display: block !important;} }\n"
                + "    .hide_section_on_mobile { display: none !important;} \n"
                + "    @media only screen and (min-width: 480px) { \n"
                + "        .hide_section_on_mobile { \n"
                + "            display: table !important;\n"
                + "        } \n"
                + "        div.hide_section_on_mobile { \n"
                + "            display: block !important;\n"
                + "        }\n"
                + "    }\n"
                + "    .hide_on_desktop { display: block !important;} \n"
                + "    @media only screen and (min-width: 480px) { .hide_on_desktop { display: none !important;} }\n"
                + "    .hide_section_on_desktop { \n"
                + "        display: table !important;\n"
                + "        width: 100%%;\n"
                + "    } \n"
                + "    @media only screen and (min-width: 480px) { .hide_section_on_desktop { display: none !important;} }\n"
                + "    p, h1, h2, h3 {\n"
                + "        margin: 0px;\n"
                + "    }\n"
                + "    ul, li, ol {\n"
                + "      font-size: 11px;\n"
                + "      font-family: Ubuntu, Helvetica, Arial;\n"
                + "    }\n"
                + "    a {\n"
                + "        text-decoration: none;\n"
                + "        color: inherit;\n"
                + "    }\n"
                + "    @media only screen and (max-width:480px) {\n"
                + "        .mj-column-per-100 { width:100%%!important; max-width:100%%!important; }\n"
                + "        .mj-column-per-100 > .mj-column-per-100 { width:100%%!important; max-width:100%%!important; }\n"
                + "    }\n"
                + "    .mj-column-per-100 [class^=\"mj-column-per-\"] {\n"
                + "        line-height: normal;\n"
                + "    }\n"
                + "    .mj-button-full a {\n"
                + "        display: block !important;\n"
                + "    }\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body style=\"word-spacing:normal;background-color:#FFFFFF;\">\n"
                + "    <div style=\"background-color:#FFFFFF;\">\n"
                + "      <!--[if mso | IE]><table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" role=\"presentation\" style=\"width:600px;\" width=\"600\" ><tr><td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\"><![endif]-->\n"
                + "      <div style=\"margin:0px auto;max-width:600px;\">\n"
                + "        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%%;\">\n"
                + "          <tbody>\n"
                + "            <tr>\n"
                + "              <td style=\"direction:ltr;font-size:0px;padding:9px 0px 9px 0px;text-align:center;\">\n"
                + "                <!--[if mso | IE]><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td class=\"\" style=\"vertical-align:top;width:600px;\" ><![endif]-->\n"
                + "                <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%%;\">\n"
                + "                  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%%\">\n"
                + "                    <tbody>\n"
                + "                      <tr>\n"
                + "                        <td align=\"left\" style=\"font-size:0px;padding:15px 15px 15px 15px;word-break:break-word;\">\n"
                + "                          <div style=\"font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1.5;text-align:left;color:#000000;\">\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><strong><span style=\"font-size: 12px;\">Good day,&nbsp;</span></strong></p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Thank you for your request. To complete the verification process, please use the following code:</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Verification Code: %s<br>Enter this code on the verification page to confirm your identity.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Note:<br>This verification code is valid for the next 3 minutes. If you did not request this verification, please disregard this email.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><br>For security purposes, please do not share this code with anyone.<br>If you need further assistance, feel free to contact us.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Thank you for choosing Trippers' Gear Rental PH. We look forward to finalizing your rental agreement.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Best regards,<br>%s<br>%s<br>Trippers' Gear Rental PH<br>%s</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p></div>\n"
                + "                        </td>\n"
                + "                      </tr>\n"
                + "                    </tbody>\n"
                + "                  </table>\n"
                + "                </div>\n"
                + "              </td>\n"
                + "            </tr>\n"
                + "          </tbody>\n"
                + "        </table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </body>\n"
                + "</html>", code, name, position, email);

        mimeMessage.setContent(content, "text/html; charset=utf-8");
        emailSender.send(mimeMessage);
    }

    @Async
    public void sendContract(String receiverAddress, MultipartFile contract)
            throws MessagingException {
        MimeMessage mimeMessage = emailSender.createMimeMessage();
        mimeMessage.setFrom(adminGmail);
        mimeMessage.setRecipient(RecipientType.TO, new InternetAddress(receiverAddress));
        mimeMessage.setSubject("Rental Contract Ready for Review and Signature");

        String content = String.format("<!doctype html>\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                + "  <head>\n"
                + "    <title></title>\n"
                + "    <!--[if !mso]><!-->\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <!--<![endif]-->\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "    <style type=\"text/css\">\n"
                + "      #outlook a { padding:0; }\n"
                + "      body { margin:0;padding:0;-webkit-text-size-adjust:100%%;-ms-text-size-adjust:100%%; }\n"
                + "      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }\n"
                + "      img { border:0;height:auto;line-height:100%%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }\n"
                + "      p { display:block;margin:13px 0; }\n"
                + "    </style>\n"
                + "    <!--[if mso]>\n"
                + "    <noscript>\n"
                + "    <xml>\n"
                + "    <o:OfficeDocumentSettings>\n"
                + "      <o:AllowPNG/>\n"
                + "      <o:PixelsPerInch>96</o:PixelsPerInch>\n"
                + "    </o:OfficeDocumentSettings>\n"
                + "    </xml>\n"
                + "    </noscript>\n"
                + "    <![endif]-->\n"
                + "    <!--[if lte mso 11]>\n"
                + "    <style type=\"text/css\">\n"
                + "      .mj-outlook-group-fix { width:100%% !important; }\n"
                + "    </style>\n"
                + "    <![endif]-->\n"
                + "    <!--[if !mso]><!-->\n"
                + "    <link href=\"https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700\" rel=\"stylesheet\" type=\"text/css\">\n"
                + "    <link href=\"https://fonts.googleapis.com/css?family=Cabin:400,700\" rel=\"stylesheet\" type=\"text/css\">\n"
                + "    <style type=\"text/css\">\n"
                + "      @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);\n"
                + "      @import url(https://fonts.googleapis.com/css?family=Cabin:400,700);\n"
                + "    </style>\n"
                + "    <!--<![endif]-->\n"
                + "    <style type=\"text/css\">\n"
                + "      @media only screen and (min-width:480px) {\n"
                + "        .mj-column-per-100 { width:100%% !important; max-width: 100%%; }\n"
                + "      }\n"
                + "    </style>\n"
                + "    <style media=\"screen and (min-width:480px)\">\n"
                + "      .moz-text-html .mj-column-per-100 { width:100%% !important; max-width: 100%%; }\n"
                + "    </style>\n"
                + "    <style type=\"text/css\"></style>\n"
                + "    <style type=\"text/css\">\n"
                + "    .hide_on_mobile { display: none !important;} \n"
                + "    @media only screen and (min-width: 480px) { .hide_on_mobile { display: block !important;} }\n"
                + "    .hide_section_on_mobile { display: none !important;} \n"
                + "    @media only screen and (min-width: 480px) { \n"
                + "        .hide_section_on_mobile { \n"
                + "            display: table !important;\n"
                + "        } \n"
                + "        div.hide_section_on_mobile { \n"
                + "            display: block !important;\n"
                + "        }\n"
                + "    }\n"
                + "    .hide_on_desktop { display: block !important;} \n"
                + "    @media only screen and (min-width: 480px) { .hide_on_desktop { display: none !important;} }\n"
                + "    .hide_section_on_desktop { \n"
                + "        display: table !important;\n"
                + "        width: 100%%;\n"
                + "    } \n"
                + "    @media only screen and (min-width: 480px) { .hide_section_on_desktop { display: none !important;} }\n"
                + "    p, h1, h2, h3 {\n"
                + "        margin: 0px;\n"
                + "    }\n"
                + "    ul, li, ol {\n"
                + "      font-size: 11px;\n"
                + "      font-family: Ubuntu, Helvetica, Arial;\n"
                + "    }\n"
                + "    a {\n"
                + "        text-decoration: none;\n"
                + "        color: inherit;\n"
                + "    }\n"
                + "    @media only screen and (max-width:480px) {\n"
                + "        .mj-column-per-100 { width:100%%!important; max-width:100%%!important; }\n"
                + "        .mj-column-per-100 > .mj-column-per-100 { width:100%%!important; max-width:100%%!important; }\n"
                + "    }\n"
                + "    .mj-column-per-100 [class^=\"mj-column-per-\"] {\n"
                + "        line-height: normal;\n"
                + "    }\n"
                + "    .mj-button-full a {\n"
                + "        display: block !important;\n"
                + "    }\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body style=\"word-spacing:normal;background-color:#FFFFFF;\">\n"
                + "    <div style=\"background-color:#FFFFFF;\">\n"
                + "      <!--[if mso | IE]><table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" role=\"presentation\" style=\"width:600px;\" width=\"600\" ><tr><td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\"><![endif]-->\n"
                + "      <div style=\"margin:0px auto;max-width:600px;\">\n"
                + "        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%%;\">\n"
                + "          <tbody>\n"
                + "            <tr>\n"
                + "              <td style=\"direction:ltr;font-size:0px;padding:9px 0px 9px 0px;text-align:center;\">\n"
                + "                <!--[if mso | IE]><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td class=\"\" style=\"vertical-align:top;width:600px;\" ><![endif]-->\n"
                + "                <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%%;\">\n"
                + "                  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%%\">\n"
                + "                    <tbody>\n"
                + "                      <tr>\n"
                + "                        <td align=\"left\" style=\"font-size:0px;padding:15px 15px 15px 15px;word-break:break-word;\">\n"
                + "                          <div style=\"font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1.5;text-align:left;color:#000000;\">\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><strong><span style=\"font-size: 12px;\">Good day,&nbsp;</span></strong></p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">We are pleased to inform you that your rental application has been successfully processed. Your rental contract is now ready for your review and signature. Please find the attached contract for your reference.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">To proceed, kindly review the document and return it to us with your e-signature at your earliest convenience.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">If you did not request a contract for this account, please feel free to disregard this email.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Should you have any questions or require assistance, don't hesitate to reach out. We&rsquo;re happy to help.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Thank you for choosing Trippers' Gear Rental PH. We look forward to finalizing your rental agreement.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Best regards,<br>%s<br>%s<br>Trippers' Gear Rental PH<br>%s</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                          </div>\n"
                + "                        </td>\n"
                + "                      </tr>\n"
                + "                    </tbody>\n"
                + "                  </table>\n"
                + "                </div>\n"
                + "              </td>\n"
                + "            </tr>\n"
                + "          </tbody>\n"
                + "        </table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </body>\n"
                + "</html>", name, position, email);

        BodyPart messageBodyPart = new MimeBodyPart();
        messageBodyPart.setContent(content, "text/html; charset=utf-8");
        MimeBodyPart attachmentBodyPart = new MimeBodyPart();

        try {
            Path tempFile = Files.createFile(Paths.get(String.format("/servers/file.tmp")));
            contract.transferTo(tempFile);
            attachmentBodyPart.attachFile(tempFile.toFile());
            Files.delete(Paths.get("/servers/file.tmp"));
        } catch (IOException e) {
            try {
                Files.delete(Paths.get("/servers/file.tmp"));
            } catch (IOException _) {
            }
            throw new IllegalArgumentException("The contract file has corrupted. Try sending it again.");
        }

        MimeMultipart multipart = new MimeMultipart();
        multipart.addBodyPart(messageBodyPart);
        multipart.addBodyPart(attachmentBodyPart);

        mimeMessage.setContent(multipart);
        emailSender.send(mimeMessage);
    }

    @Async
    public void sendConfirmationSignedContract(String receiverAddress, String requestBookingReference,
            ZonedDateTime bookingDateFrom, ZonedDateTime bookingDateUntil, BigDecimal amount)
            throws MessagingException {
        MimeMessage mimeMessage = emailSender.createMimeMessage();
        mimeMessage.setFrom(adminGmail);
        mimeMessage.setRecipient(RecipientType.TO, new InternetAddress(receiverAddress));
        mimeMessage.setSubject("Confirmation of Your Signed Rental Contract");
        String content = String.format("<!doctype html>\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                + "<head>\n"
                + "  <title></title>\n"
                + "  <!--[if !mso]><!-->\n"
                + "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n"
                + "  <!--<![endif]-->\n"
                + "  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n"
                + "  <style type=\"text/css\">\n"
                + "    #outlook a { padding: 0; }\n"
                + "    body { margin: 0; padding: 0; -webkit-text-size-adjust: 100%%; -ms-text-size-adjust: 100%%; }\n"
                + "    table, td { border-collapse: collapse; mso-table-lspace: 0pt; mso-table-rspace: 0pt; }\n"
                + "    img { border: 0; height: auto; line-height: 100%%; outline: none; text-decoration: none; -ms-interpolation-mode: bicubic; }\n"
                + "    p { display: block; margin: 13px 0; }\n"
                + "  </style>\n"
                + "  <!--[if mso]>\n"
                + "    <noscript>\n"
                + "      <xml>\n"
                + "        <o:OfficeDocumentSettings>\n"
                + "          <o:AllowPNG />\n"
                + "          <o:PixelsPerInch>96</o:PixelsPerInch>\n"
                + "        </o:OfficeDocumentSettings>\n"
                + "      </xml>\n"
                + "    </noscript>\n"
                + "  <![endif]-->\n"
                + "  <!--[if lte mso 11]>\n"
                + "    <style type=\"text/css\">\n"
                + "      .mj-outlook-group-fix { width: 100%% !important; }\n"
                + "    </style>\n"
                + "  <![endif]-->\n"
                + "  <!--[if !mso]><!-->\n"
                + "  <link href=\"https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700\" rel=\"stylesheet\" type=\"text/css\" />\n"
                + "  <link href=\"https://fonts.googleapis.com/css?family=Cabin:400,700\" rel=\"stylesheet\" type=\"text/css\" />\n"
                + "  <style type=\"text/css\">\n"
                + "    @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);\n"
                + "    @import url(https://fonts.googleapis.com/css?family=Cabin:400,700);\n"
                + "  </style>\n"
                + "  <!--<![endif]-->\n"
                + "  <style type=\"text/css\">\n"
                + "    @media only screen and (min-width: 480px) {\n"
                + "      .mj-column-per-100 { width: 100%% !important; max-width: 100%%; }\n"
                + "    }\n"
                + "  </style>\n"
                + "  <style media=\"screen and (min-width:480px)\">\n"
                + "    .moz-text-html .mj-column-per-100 { width: 100%% !important; max-width: 100%%; }\n"
                + "  </style>\n"
                + "  <style type=\"text/css\"></style>\n"
                + "  <style type=\"text/css\">\n"
                + "    .hide_on_mobile { display: none !important; }\n"
                + "    @media only screen and (min-width: 480px) {\n"
                + "      .hide_on_mobile { display: block !important; }\n"
                + "    }\n"
                + "    .hide_section_on_mobile { display: none !important; }\n"
                + "    @media only screen and (min-width: 480px) {\n"
                + "      .hide_section_on_mobile { display: table !important; }\n"
                + "      div.hide_section_on_mobile { display: block !important; }\n"
                + "    }\n"
                + "    .hide_on_desktop { display: block !important; }\n"
                + "    @media only screen and (min-width: 480px) {\n"
                + "      .hide_on_desktop { display: none !important; }\n"
                + "    }\n"
                + "    .hide_section_on_desktop { display: table !important; width: 100%%; }\n"
                + "    @media only screen and (min-width: 480px) {\n"
                + "      .hide_section_on_desktop { display: none !important; }\n"
                + "    }\n"
                + "    p, h1, h2, h3 { margin: 0px; }\n"
                + "    ul, li, ol { font-size: 11px; font-family: Ubuntu, Helvetica, Arial; }\n"
                + "    a { text-decoration: none; color: inherit; }\n"
                + "    @media only screen and (max-width: 480px) {\n"
                + "      .mj-column-per-100 { width: 100%% !important; max-width: 100%% !important; }\n"
                + "      .mj-column-per-100 > .mj-column-per-100 { width: 100%% !important; max-width: 100%% !important; }\n"
                + "    }\n"
                + "    .mj-column-per-100 [class^=\"mj-column-per-\"] { line-height: normal; }\n"
                + "    .mj-button-full a { display: block !important; }\n"
                + "  </style>\n"
                + "</head>\n"
                + "<body style=\"word-spacing: normal; background-color: #ffffff\">\n"
                + "<div style=\"background-color: #ffffff\">\n"
                + "<div style=\"margin: 0px auto; max-width: 600px\">\n"
                + "<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width: 100%%\">\n"
                + "  <tbody>\n"
                + "    <tr>\n"
                + "      <td style=\"direction: ltr; font-size: 0px; padding: 9px 0px 9px 0px; text-align: center;\">\n"
                + "        <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size: 0px; text-align: left; direction: ltr; display: inline-block; vertical-align: top; width: 100%%;\">\n"
                + "          <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align: top\" width=\"100%%\">\n"
                + "            <tbody>\n"
                + "              <tr>\n"
                + "                <td align=\"left\" style=\"font-size: 0px; padding: 15px 15px 15px 15px; word-break: break-word;\">\n"
                + "                  <div style=\"font-family: Ubuntu, Helvetica, Arial, sans-serif; font-size: 13px; line-height: 1.5; text-align: left; color: #000000;\">\n"
                + "                    <p><strong><span style=\"font-size: 12px;\">Good day, </span></strong><br><br></p>"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">I hope this email finds you well.</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">We are pleased to confirm that we have successfully received and processed your signed rental contract. Your reservation is now officially secured.</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">Key Details of Your Reservation:</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">Booking Reference: %s</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">Rental Period: %s : %s</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">Total Amount: %s</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">Next Steps</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">Confirmation: You will shortly receive a detailed invoice reflecting the contract terms and total amount.</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">Payment Reminder: If any additional payments (such as the balance or security deposit) are due, a separate notification will be sent to you with payment instructions.</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">Arrival Instructions: Please ensure you have a valid credit/debit card or cash ready for the pre-authorization/deposit for the rental items. The deposit will be released after the items are returned and inspected, with no charges unless necessary.</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">Thank you for choosing Trippers' Gear Rental PH. We look forward to welcoming you and ensuring you have a smooth and enjoyable experience.</span></p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                    <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Best regards,<br>%s<br>%s<br>Trippers' Gear Rental PH<br>%s</p>\n"
                + "                  </div>\n"
                + "                </td>\n"
                + "              </tr>\n"
                + "            </tbody>\n"
                + "          </table>\n"
                + "        </div>\n"
                + "      </td>\n"
                + "    </tr>\n"
                + "  </tbody>\n"
                + "</table>\n"
                + "</div>\n"
                + "</div>\n"
                + "</body>\n"
                + "</html>", requestBookingReference, bookingDateFrom.toString(), bookingDateUntil.toString(),
                amount.toPlainString(), name, position, email);
        mimeMessage.setContent(content, "text/html; charset=utf-8");
        emailSender.send(mimeMessage);
    }

    @Async
    public void sendRestrictedFundsCheckoutId(String receiverAddress, String checkoutId) throws MessagingException {
        MimeMessage mimeMessage = emailSender.createMimeMessage();
        mimeMessage.setFrom(adminGmail);
        mimeMessage.setRecipient(RecipientType.TO, new InternetAddress(receiverAddress));
        mimeMessage.setSubject("Arrival Instructions and Checkout ID for Deposit Processing");
        String content = String.format("<!doctype html>\n"
                + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\n"
                + "  <head>\n"
                + "    <title></title>\n"
                + "    <!--[if !mso]><!-->\n"
                + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n"
                + "    <!--<![endif]-->\n"
                + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
                + "    <style type=\"text/css\">\n"
                + "      #outlook a { padding:0; }\n"
                + "      body { margin:0;padding:0;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%; }\n"
                + "      table, td { border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt; }\n"
                + "      img { border:0;height:auto;line-height:100%; outline:none;text-decoration:none;-ms-interpolation-mode:bicubic; }\n"
                + "      p { display:block;margin:13px 0; }\n"
                + "    </style>\n"
                + "    <!--[if mso]>\n"
                + "    <noscript>\n"
                + "    <xml>\n"
                + "    <o:OfficeDocumentSettings>\n"
                + "      <o:AllowPNG/>\n"
                + "      <o:PixelsPerInch>96</o:PixelsPerInch>\n"
                + "    </o:OfficeDocumentSettings>\n"
                + "    </xml>\n"
                + "    </noscript>\n"
                + "    <![endif]-->\n"
                + "    <!--[if lte mso 11]>\n"
                + "    <style type=\"text/css\">\n"
                + "      .mj-outlook-group-fix { width:100% !important; }\n"
                + "    </style>\n"
                + "    <![endif]-->\n"
                + "    <!--[if !mso]><!-->\n"
                + "    <link href=\"https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700\" rel=\"stylesheet\" type=\"text/css\">\n"
                + "    <link href=\"https://fonts.googleapis.com/css?family=Cabin:400,700\" rel=\"stylesheet\" type=\"text/css\">\n"
                + "    <style type=\"text/css\">\n"
                + "      @import url(https://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700);\n"
                + "      @import url(https://fonts.googleapis.com/css?family=Cabin:400,700);\n"
                + "    </style>\n"
                + "    <!--<![endif]-->\n"
                + "    <style type=\"text/css\">\n"
                + "      @media only screen and (min-width:480px) {\n"
                + "        .mj-column-per-100 { width:100% !important; max-width: 100%; }\n"
                + "      }\n"
                + "    </style>\n"
                + "    <style media=\"screen and (min-width:480px)\">\n"
                + "      .moz-text-html .mj-column-per-100 { width:100% !important; max-width: 100%; }\n"
                + "    </style>\n"
                + "    <style type=\"text/css\"></style>\n"
                + "    <style type=\"text/css\">\n"
                + "    .hide_on_mobile { display: none !important;} \n"
                + "    @media only screen and (min-width: 480px) { .hide_on_mobile { display: block !important;} }\n"
                + "    .hide_section_on_mobile { display: none !important;} \n"
                + "    @media only screen and (min-width: 480px) { \n"
                + "        .hide_section_on_mobile { \n"
                + "            display: table !important;\n"
                + "        } \n"
                + "        div.hide_section_on_mobile { \n"
                + "            display: block !important;\n"
                + "        }\n"
                + "    }\n"
                + "    .hide_on_desktop { display: block !important;} \n"
                + "    @media only screen and (min-width: 480px) { .hide_on_desktop { display: none !important;} }\n"
                + "    .hide_section_on_desktop { \n"
                + "        display: table !important;\n"
                + "        width: 100%;\n"
                + "    } \n"
                + "    @media only screen and (min-width: 480px) { .hide_section_on_desktop { display: none !important;} }\n"
                + "    p, h1, h2, h3 {\n"
                + "        margin: 0px;\n"
                + "    }\n"
                + "    ul, li, ol {\n"
                + "      font-size: 11px;\n"
                + "      font-family: Ubuntu, Helvetica, Arial;\n"
                + "    }\n"
                + "    a {\n"
                + "        text-decoration: none;\n"
                + "        color: inherit;\n"
                + "    }\n"
                + "    @media only screen and (max-width:480px) {\n"
                + "        .mj-column-per-100 { width:100%!important; max-width:100%!important; }\n"
                + "        .mj-column-per-100 > .mj-column-per-100 { width:100%!important; max-width:100%!important; }\n"
                + "    }\n"
                + "    .mj-column-per-100 [class^=\"mj-column-per-\"] {\n"
                + "        line-height: normal;\n"
                + "    }\n"
                + "    .mj-button-full a {\n"
                + "        display: block !important;\n"
                + "    }\n"
                + "    </style>\n"
                + "  </head>\n"
                + "  <body style=\"word-spacing:normal;background-color:#FFFFFF;\">\n"
                + "    <div style=\"background-color:#FFFFFF;\">\n"
                + "      <!--[if mso | IE]><table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"\" role=\"presentation\" style=\"width:600px;\" width=\"600\" ><tr><td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\"><![endif]-->\n"
                + "      <div style=\"margin:0px auto;max-width:600px;\">\n"
                + "        <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">\n"
                + "          <tbody>\n"
                + "            <tr>\n"
                + "              <td style=\"direction:ltr;font-size:0px;padding:9px 0px 9px 0px;text-align:center;\">\n"
                + "                <!--[if mso | IE]><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td class=\"\" style=\"vertical-align:top;width:600px;\" ><![endif]-->\n"
                + "                <div class=\"mj-column-per-100 mj-outlook-group-fix\" style=\"font-size:0px;text-align:left;direction:ltr;display:inline-block;vertical-align:top;width:100%;\">\n"
                + "                  <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:top;\" width=\"100%\">\n"
                + "                    <tbody>\n"
                + "                      <tr>\n"
                + "                        <td align=\"left\" style=\"font-size:0px;padding:15px 15px 15px 15px;word-break:break-word;\">\n"
                + "                          <div style=\"font-family:Ubuntu, Helvetica, Arial, sans-serif;font-size:13px;line-height:1.5;text-align:left;color:#000000;\">\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><strong><span style=\"font-size: 12px;\">Good day,&nbsp;</span></strong></p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">We are looking forward to welcoming you and ensuring a smooth start to your rental experience. To facilitate your check-in process, please follow the instructions below regarding your deposit.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Checkout ID for Deposit Processing:<br>Your unique Checkout ID is: %s.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Kindly provide this ID to our admin team upon arrival so we can process your deposit.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Deposit Methods:<br>The deposit can be processed using one of the following methods:</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Cash: If you prefer to pay the deposit in cash, please bring the exact amount with you upon arrival.<br>Pre-authorization (Card): Alternatively, you can provide your credit/debit card details for a pre-authorization. This will temporarily hold the deposit amount and will be released once the rental items are returned and inspected, with no charge unless necessary.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><br>What You Need to Provide:<br>Checkout ID (for deposit processing)<br>Valid ID (e.g., driver&rsquo;s license, passport)</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><br>Payment method: Cash or credit/debit card for pre-authorization<br>If you have any questions or require further assistance, please feel free to contact us. Our team is here to help and ensure you have a seamless experience.</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\"><span style=\"font-size: 12px\">Thank you for choosing Trippers' Gear Rental PH. We look forward to welcoming you and ensuring you have a smooth and enjoyable experience.</span></p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">Best regards,<br>%s<br>%s<br>Trippers' Gear Rental PH<br>%s</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p>\n"
                + "                            <p style=\"font-family: Helvetica, Arial, sans-serif; font-size: 11px;\">&nbsp;</p></div>\n"
                + "                        </td>\n"
                + "                      </tr>\n"
                + "                    </tbody>\n"
                + "                  </table>\n"
                + "                </div>\n"
                + "              </td>\n"
                + "            </tr>\n"
                + "          </tbody>\n"
                + "        </table>\n"
                + "      </div>\n"
                + "    </div>\n"
                + "  </body>\n"
                + "</html>", checkoutId, name, position, email);
        mimeMessage.setContent(content, "text/html; charset=utf-8");
        emailSender.send(mimeMessage);
    }
}
